# Secret khusus untuk lingkungan Production
apiVersion: v1
kind: Secret
metadata:
  name: app-secret # Nama Secret (sama dengan Dev, tapi di namespace berbeda)
  namespace: prod # Ditempatkan di namespace 'prod'
type: Opaque
data:
  API_KEY: bmlsYWlfc2VjcmV0X2FuZGFfZGV2= # Contoh: base64 encoding dari "kunci_rahasia_prod_456"
